### ISSUE TITLE
Errors with some larger maps

### ISSUE THREAD

**Issue by thagrasshoppa** [m42e/dd2vtt-stick#1]
C:\Users\xxxx\Desktop\MapJoiner>python3 ./stick.py -g WPM-Area1.dd2vtt WPM-Area2.dd2vtt WPM-Area3.dd2vtt WPM-Area4.dd2vtt WPM-Area5.dd2vtt WPM-Area6.dd2vtt
INFO:__main__:Created grid with 3 x 2
INFO:__main__:Created canvas with size of 8610 x 5600
Traceback (most recent call last):
  File "./stick.py", line 208, in <module>
    main()
  File "./stick.py", line 203, in main
    c = Canvas(files, mode, image_type=image_type)
  File "./stick.py", line 60, in __init__
    self.add_images()
  File "./stick.py", line 135, in add_images
    self.canvas.save(self.canvas_io, image_type)
NameError: name 'image_type' is not defined

**Comment by m42e** [comment]
Wolle you min upload the original files somewhere?

**Comment by thagrasshoppa** [comment]
Sure!

Thanks for looking at this, and also a heartfelt thanks for creating it in
the first place!!!

https://1drv.ms/u/s!AmJfVHWVCmGihd8BuQE5Un9vmNzYoQ?e=YzyL4P

**Comment by m42e** [comment]
Thanks for sharing, just checked that it is working 👍

**Comment by thagrasshoppa** [comment]
When I import that resultant file, I get error in Maptool...I will try it
in another VTT...

Can you chat about things like this?  Or is Email your only option?

Tim

**Comment by thagrasshoppa** [comment]
I have a discord, and I have paid Zoom account, if you can chat...

https://discord.gg/mTeBZK

Tim
